# Background and foreground colors
background = #1e1411
foreground = #bdb09d

# Standard colors
palette = 0=#1e1411
palette = 1=#5a0a0a
palette = 2=#921416
palette = 3=#856839
palette = 4=#4d3a2b
palette = 5=#c2b28c
palette = 6=#e4d8c1
palette = 7=#9c8b74

# Bright colors
palette = 8=#352924
palette = 9=#821515
palette = 10=#b8282b
palette = 11=#a68a55
palette = 12=#705c4b
palette = 13=#ded2b3
palette = 14=#f5efe1
palette = 15=#bdb09d
