background            #1e1411
foreground            #bdb09d

# black
color0  #1e1411
color8  #352924

# red
color1  #5a0a0a
color9  #821515

# green
color2  #921416
color10 #b8282b

# yellow
color3  #856839
color11 #a68a55

# blue
color4  #4d3a2b
color12 #705c4b

# magenta
color5  #c2b28c
color13 #ded2b3

#cyan
color6  #e4d8c1
color14 #f5efe1

#white
color7  #9c8b74
color15 #bdb09d


